name: Lint
permissions:
  contents: read

on:
  push:
    paths:
      - 'nvdinterface/**.py'
      - '.github/workflows/lint.yml'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./nvdinterface"
