name: Test
permissions:
  contents: read

on:
  push:
    paths:
      - 'nvdinterface/**'
      - 'tests/**'
      - '.github/workflows/test.yml'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade poetry
          poetry install --no-interaction -E dev
      - name: Test with unittest
        run: poetry run python -m unittest discover tests/
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
